/*
 * generated by Xtext 2.25.0
 */
package org.xtext.example.iml;


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
public class ExtendedIMLStandaloneSetup extends ExtendedIMLStandaloneSetupGenerated {

	public static void doSetup() {
		new ExtendedIMLStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}
