/*
 * generated by Xtext 2.25.0
 */
package org.xtext.example.iml.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
public class ExtendedIMLUiModule extends AbstractExtendedIMLUiModule {

	public ExtendedIMLUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
