/*
 * generated by Xtext 2.25.0
 */
package org.xtext.example.iml.parser.antlr;

import com.google.inject.Inject;
import org.eclipse.xtext.parser.antlr.AbstractAntlrParser;
import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import org.xtext.example.iml.parser.antlr.internal.InternalExtendedIMLParser;
import org.xtext.example.iml.services.ExtendedIMLGrammarAccess;

public class ExtendedIMLParser extends AbstractAntlrParser {

	@Inject
	private ExtendedIMLGrammarAccess grammarAccess;

	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	

	@Override
	protected InternalExtendedIMLParser createParser(XtextTokenStream stream) {
		return new InternalExtendedIMLParser(stream, getGrammarAccess());
	}

	@Override 
	protected String getDefaultRuleName() {
		return "Model";
	}

	public ExtendedIMLGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(ExtendedIMLGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
