/**
 * generated by Xtext 2.25.0
 */
package org.xtext.example.iml.extendedIML.impl;

import org.eclipse.emf.ecore.EClass;

import org.xtext.example.iml.extendedIML.EqualizeOperation;
import org.xtext.example.iml.extendedIML.ExtendedIMLPackage;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Equalize Operation</b></em>'.
 * <!-- end-user-doc -->
 *
 * @generated
 */
public class EqualizeOperationImpl extends OperatorImpl implements EqualizeOperation
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected EqualizeOperationImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return ExtendedIMLPackage.Literals.EQUALIZE_OPERATION;
  }

} //EqualizeOperationImpl
