/**
 * generated by Xtext 2.25.0
 */
package org.xtext.example.iml.extendedIML.impl;

import org.eclipse.emf.ecore.EClass;

import org.xtext.example.iml.extendedIML.ExtendedIMLPackage;
import org.xtext.example.iml.extendedIML.SaveOperation;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Save Operation</b></em>'.
 * <!-- end-user-doc -->
 *
 * @generated
 */
public class SaveOperationImpl extends OperatorImpl implements SaveOperation
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected SaveOperationImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return ExtendedIMLPackage.Literals.SAVE_OPERATION;
  }

} //SaveOperationImpl
