/*
 * generated by Xtext 2.25.0
 */
package org.xtext.example.iml.ui.tests;

import com.google.inject.Injector;
import org.eclipse.xtext.testing.IInjectorProvider;
import org.xtext.example.iml.ui.internal.ImlActivator;

public class ExtendedIMLUiInjectorProvider implements IInjectorProvider {

	@Override
	public Injector getInjector() {
		return ImlActivator.getInstance().getInjector("org.xtext.example.iml.ExtendedIML");
	}

}
