/**
 * generated by Xtext 2.25.0
 */
package org.xtext.example.iml.extendedIML;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Dir Importer</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.iml.extendedIML.DirImporter#getPathDir <em>Path Dir</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.iml.extendedIML.ExtendedIMLPackage#getDirImporter()
 * @model
 * @generated
 */
public interface DirImporter extends Importer
{
  /**
   * Returns the value of the '<em><b>Path Dir</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Path Dir</em>' attribute.
   * @see #setPathDir(String)
   * @see org.xtext.example.iml.extendedIML.ExtendedIMLPackage#getDirImporter_PathDir()
   * @model
   * @generated
   */
  String getPathDir();

  /**
   * Sets the value of the '{@link org.xtext.example.iml.extendedIML.DirImporter#getPathDir <em>Path Dir</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Path Dir</em>' attribute.
   * @see #getPathDir()
   * @generated
   */
  void setPathDir(String value);

} // DirImporter
