/**
 * generated by Xtext 2.25.0
 */
package org.xtext.example.iml.extendedIML;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Exporter</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.iml.extendedIML.Exporter#getVar <em>Var</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.iml.extendedIML.ExtendedIMLPackage#getExporter()
 * @model
 * @generated
 */
public interface Exporter extends AbstractElement
{
  /**
   * Returns the value of the '<em><b>Var</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Var</em>' attribute.
   * @see #setVar(String)
   * @see org.xtext.example.iml.extendedIML.ExtendedIMLPackage#getExporter_Var()
   * @model
   * @generated
   */
  String getVar();

  /**
   * Sets the value of the '{@link org.xtext.example.iml.extendedIML.Exporter#getVar <em>Var</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Var</em>' attribute.
   * @see #getVar()
   * @generated
   */
  void setVar(String value);

} // Exporter
