/**
 * generated by Xtext 2.25.0
 */
package org.xtext.example.iml.extendedIML;

import org.eclipse.emf.ecore.EFactory;

/**
 * <!-- begin-user-doc -->
 * The <b>Factory</b> for the model.
 * It provides a create method for each non-abstract class of the model.
 * <!-- end-user-doc -->
 * @see org.xtext.example.iml.extendedIML.ExtendedIMLPackage
 * @generated
 */
public interface ExtendedIMLFactory extends EFactory
{
  /**
   * The singleton instance of the factory.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  ExtendedIMLFactory eINSTANCE = org.xtext.example.iml.extendedIML.impl.ExtendedIMLFactoryImpl.init();

  /**
   * Returns a new object of class '<em>Model</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Model</em>'.
   * @generated
   */
  Model createModel();

  /**
   * Returns a new object of class '<em>Abstract Element</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Abstract Element</em>'.
   * @generated
   */
  AbstractElement createAbstractElement();

  /**
   * Returns a new object of class '<em>Exporter</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Exporter</em>'.
   * @generated
   */
  Exporter createExporter();

  /**
   * Returns a new object of class '<em>Save</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Save</em>'.
   * @generated
   */
  Save createSave();

  /**
   * Returns a new object of class '<em>Show</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Show</em>'.
   * @generated
   */
  Show createShow();

  /**
   * Returns a new object of class '<em>Importer</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Importer</em>'.
   * @generated
   */
  Importer createImporter();

  /**
   * Returns a new object of class '<em>Image Importer</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Image Importer</em>'.
   * @generated
   */
  ImageImporter createImageImporter();

  /**
   * Returns a new object of class '<em>Dir Importer</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Dir Importer</em>'.
   * @generated
   */
  DirImporter createDirImporter();

  /**
   * Returns a new object of class '<em>Operator</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Operator</em>'.
   * @generated
   */
  Operator createOperator();

  /**
   * Returns a new object of class '<em>Rotate Operation</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Rotate Operation</em>'.
   * @generated
   */
  RotateOperation createRotateOperation();

  /**
   * Returns a new object of class '<em>Filter Operation</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Filter Operation</em>'.
   * @generated
   */
  FilterOperation createFilterOperation();

  /**
   * Returns a new object of class '<em>Blur Operation</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Blur Operation</em>'.
   * @generated
   */
  BlurOperation createBlurOperation();

  /**
   * Returns a new object of class '<em>Equalize Operation</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Equalize Operation</em>'.
   * @generated
   */
  EqualizeOperation createEqualizeOperation();

  /**
   * Returns the package supported by this factory.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the package supported by this factory.
   * @generated
   */
  ExtendedIMLPackage getExtendedIMLPackage();

} //ExtendedIMLFactory
