/**
 * generated by Xtext 2.25.0
 */
package org.xtext.example.iml.extendedIML;

import org.eclipse.emf.ecore.EAttribute;
import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.emf.ecore.EReference;

/**
 * <!-- begin-user-doc -->
 * The <b>Package</b> for the model.
 * It contains accessors for the meta objects to represent
 * <ul>
 *   <li>each class,</li>
 *   <li>each feature of each class,</li>
 *   <li>each enum,</li>
 *   <li>and each data type</li>
 * </ul>
 * <!-- end-user-doc -->
 * @see org.xtext.example.iml.extendedIML.ExtendedIMLFactory
 * @model kind="package"
 * @generated
 */
public interface ExtendedIMLPackage extends EPackage
{
  /**
   * The package name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNAME = "extendedIML";

  /**
   * The package namespace URI.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_URI = "http://www.xtext.org/example/iml/ExtendedIML";

  /**
   * The package namespace name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_PREFIX = "extendedIML";

  /**
   * The singleton instance of the package.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  ExtendedIMLPackage eINSTANCE = org.xtext.example.iml.extendedIML.impl.ExtendedIMLPackageImpl.init();

  /**
   * The meta object id for the '{@link org.xtext.example.iml.extendedIML.impl.ModelImpl <em>Model</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.iml.extendedIML.impl.ModelImpl
   * @see org.xtext.example.iml.extendedIML.impl.ExtendedIMLPackageImpl#getModel()
   * @generated
   */
  int MODEL = 0;

  /**
   * The feature id for the '<em><b>Elements</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MODEL__ELEMENTS = 0;

  /**
   * The number of structural features of the '<em>Model</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MODEL_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link org.xtext.example.iml.extendedIML.impl.AbstractElementImpl <em>Abstract Element</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.iml.extendedIML.impl.AbstractElementImpl
   * @see org.xtext.example.iml.extendedIML.impl.ExtendedIMLPackageImpl#getAbstractElement()
   * @generated
   */
  int ABSTRACT_ELEMENT = 1;

  /**
   * The number of structural features of the '<em>Abstract Element</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ABSTRACT_ELEMENT_FEATURE_COUNT = 0;

  /**
   * The meta object id for the '{@link org.xtext.example.iml.extendedIML.impl.ImporterImpl <em>Importer</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.iml.extendedIML.impl.ImporterImpl
   * @see org.xtext.example.iml.extendedIML.impl.ExtendedIMLPackageImpl#getImporter()
   * @generated
   */
  int IMPORTER = 2;

  /**
   * The number of structural features of the '<em>Importer</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int IMPORTER_FEATURE_COUNT = ABSTRACT_ELEMENT_FEATURE_COUNT + 0;

  /**
   * The meta object id for the '{@link org.xtext.example.iml.extendedIML.impl.ImageImporterImpl <em>Image Importer</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.iml.extendedIML.impl.ImageImporterImpl
   * @see org.xtext.example.iml.extendedIML.impl.ExtendedIMLPackageImpl#getImageImporter()
   * @generated
   */
  int IMAGE_IMPORTER = 3;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int IMAGE_IMPORTER__NAME = IMPORTER_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Imported Namespace</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int IMAGE_IMPORTER__IMPORTED_NAMESPACE = IMPORTER_FEATURE_COUNT + 1;

  /**
   * The number of structural features of the '<em>Image Importer</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int IMAGE_IMPORTER_FEATURE_COUNT = IMPORTER_FEATURE_COUNT + 2;

  /**
   * The meta object id for the '{@link org.xtext.example.iml.extendedIML.impl.DirImporterImpl <em>Dir Importer</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.iml.extendedIML.impl.DirImporterImpl
   * @see org.xtext.example.iml.extendedIML.impl.ExtendedIMLPackageImpl#getDirImporter()
   * @generated
   */
  int DIR_IMPORTER = 4;

  /**
   * The feature id for the '<em><b>Path Dir</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DIR_IMPORTER__PATH_DIR = IMPORTER_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Dir Importer</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DIR_IMPORTER_FEATURE_COUNT = IMPORTER_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link org.xtext.example.iml.extendedIML.impl.OperatorImpl <em>Operator</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.iml.extendedIML.impl.OperatorImpl
   * @see org.xtext.example.iml.extendedIML.impl.ExtendedIMLPackageImpl#getOperator()
   * @generated
   */
  int OPERATOR = 5;

  /**
   * The feature id for the '<em><b>Var</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int OPERATOR__VAR = ABSTRACT_ELEMENT_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Operator</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int OPERATOR_FEATURE_COUNT = ABSTRACT_ELEMENT_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link org.xtext.example.iml.extendedIML.impl.RotateOperationImpl <em>Rotate Operation</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.iml.extendedIML.impl.RotateOperationImpl
   * @see org.xtext.example.iml.extendedIML.impl.ExtendedIMLPackageImpl#getRotateOperation()
   * @generated
   */
  int ROTATE_OPERATION = 6;

  /**
   * The feature id for the '<em><b>Var</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ROTATE_OPERATION__VAR = OPERATOR__VAR;

  /**
   * The feature id for the '<em><b>Degree</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ROTATE_OPERATION__DEGREE = OPERATOR_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Rotate Operation</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ROTATE_OPERATION_FEATURE_COUNT = OPERATOR_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link org.xtext.example.iml.extendedIML.impl.FilterOperationImpl <em>Filter Operation</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.iml.extendedIML.impl.FilterOperationImpl
   * @see org.xtext.example.iml.extendedIML.impl.ExtendedIMLPackageImpl#getFilterOperation()
   * @generated
   */
  int FILTER_OPERATION = 7;

  /**
   * The feature id for the '<em><b>Var</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FILTER_OPERATION__VAR = OPERATOR__VAR;

  /**
   * The number of structural features of the '<em>Filter Operation</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FILTER_OPERATION_FEATURE_COUNT = OPERATOR_FEATURE_COUNT + 0;

  /**
   * The meta object id for the '{@link org.xtext.example.iml.extendedIML.impl.BlurOperationImpl <em>Blur Operation</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.iml.extendedIML.impl.BlurOperationImpl
   * @see org.xtext.example.iml.extendedIML.impl.ExtendedIMLPackageImpl#getBlurOperation()
   * @generated
   */
  int BLUR_OPERATION = 8;

  /**
   * The feature id for the '<em><b>Var</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int BLUR_OPERATION__VAR = OPERATOR__VAR;

  /**
   * The feature id for the '<em><b>Intensity</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int BLUR_OPERATION__INTENSITY = OPERATOR_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Blur Operation</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int BLUR_OPERATION_FEATURE_COUNT = OPERATOR_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link org.xtext.example.iml.extendedIML.impl.EqualizeOperationImpl <em>Equalize Operation</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.iml.extendedIML.impl.EqualizeOperationImpl
   * @see org.xtext.example.iml.extendedIML.impl.ExtendedIMLPackageImpl#getEqualizeOperation()
   * @generated
   */
  int EQUALIZE_OPERATION = 9;

  /**
   * The feature id for the '<em><b>Var</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EQUALIZE_OPERATION__VAR = OPERATOR__VAR;

  /**
   * The number of structural features of the '<em>Equalize Operation</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EQUALIZE_OPERATION_FEATURE_COUNT = OPERATOR_FEATURE_COUNT + 0;

  /**
   * The meta object id for the '{@link org.xtext.example.iml.extendedIML.impl.ShowOperationImpl <em>Show Operation</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.iml.extendedIML.impl.ShowOperationImpl
   * @see org.xtext.example.iml.extendedIML.impl.ExtendedIMLPackageImpl#getShowOperation()
   * @generated
   */
  int SHOW_OPERATION = 10;

  /**
   * The feature id for the '<em><b>Var</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SHOW_OPERATION__VAR = OPERATOR__VAR;

  /**
   * The number of structural features of the '<em>Show Operation</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SHOW_OPERATION_FEATURE_COUNT = OPERATOR_FEATURE_COUNT + 0;

  /**
   * The meta object id for the '{@link org.xtext.example.iml.extendedIML.impl.SaveOperationImpl <em>Save Operation</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.iml.extendedIML.impl.SaveOperationImpl
   * @see org.xtext.example.iml.extendedIML.impl.ExtendedIMLPackageImpl#getSaveOperation()
   * @generated
   */
  int SAVE_OPERATION = 11;

  /**
   * The feature id for the '<em><b>Var</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SAVE_OPERATION__VAR = OPERATOR__VAR;

  /**
   * The number of structural features of the '<em>Save Operation</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SAVE_OPERATION_FEATURE_COUNT = OPERATOR_FEATURE_COUNT + 0;


  /**
   * Returns the meta object for class '{@link org.xtext.example.iml.extendedIML.Model <em>Model</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Model</em>'.
   * @see org.xtext.example.iml.extendedIML.Model
   * @generated
   */
  EClass getModel();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.example.iml.extendedIML.Model#getElements <em>Elements</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Elements</em>'.
   * @see org.xtext.example.iml.extendedIML.Model#getElements()
   * @see #getModel()
   * @generated
   */
  EReference getModel_Elements();

  /**
   * Returns the meta object for class '{@link org.xtext.example.iml.extendedIML.AbstractElement <em>Abstract Element</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Abstract Element</em>'.
   * @see org.xtext.example.iml.extendedIML.AbstractElement
   * @generated
   */
  EClass getAbstractElement();

  /**
   * Returns the meta object for class '{@link org.xtext.example.iml.extendedIML.Importer <em>Importer</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Importer</em>'.
   * @see org.xtext.example.iml.extendedIML.Importer
   * @generated
   */
  EClass getImporter();

  /**
   * Returns the meta object for class '{@link org.xtext.example.iml.extendedIML.ImageImporter <em>Image Importer</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Image Importer</em>'.
   * @see org.xtext.example.iml.extendedIML.ImageImporter
   * @generated
   */
  EClass getImageImporter();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.iml.extendedIML.ImageImporter#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see org.xtext.example.iml.extendedIML.ImageImporter#getName()
   * @see #getImageImporter()
   * @generated
   */
  EAttribute getImageImporter_Name();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.iml.extendedIML.ImageImporter#getImportedNamespace <em>Imported Namespace</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Imported Namespace</em>'.
   * @see org.xtext.example.iml.extendedIML.ImageImporter#getImportedNamespace()
   * @see #getImageImporter()
   * @generated
   */
  EAttribute getImageImporter_ImportedNamespace();

  /**
   * Returns the meta object for class '{@link org.xtext.example.iml.extendedIML.DirImporter <em>Dir Importer</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Dir Importer</em>'.
   * @see org.xtext.example.iml.extendedIML.DirImporter
   * @generated
   */
  EClass getDirImporter();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.iml.extendedIML.DirImporter#getPathDir <em>Path Dir</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Path Dir</em>'.
   * @see org.xtext.example.iml.extendedIML.DirImporter#getPathDir()
   * @see #getDirImporter()
   * @generated
   */
  EAttribute getDirImporter_PathDir();

  /**
   * Returns the meta object for class '{@link org.xtext.example.iml.extendedIML.Operator <em>Operator</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Operator</em>'.
   * @see org.xtext.example.iml.extendedIML.Operator
   * @generated
   */
  EClass getOperator();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.iml.extendedIML.Operator#getVar <em>Var</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Var</em>'.
   * @see org.xtext.example.iml.extendedIML.Operator#getVar()
   * @see #getOperator()
   * @generated
   */
  EAttribute getOperator_Var();

  /**
   * Returns the meta object for class '{@link org.xtext.example.iml.extendedIML.RotateOperation <em>Rotate Operation</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Rotate Operation</em>'.
   * @see org.xtext.example.iml.extendedIML.RotateOperation
   * @generated
   */
  EClass getRotateOperation();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.iml.extendedIML.RotateOperation#getDegree <em>Degree</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Degree</em>'.
   * @see org.xtext.example.iml.extendedIML.RotateOperation#getDegree()
   * @see #getRotateOperation()
   * @generated
   */
  EAttribute getRotateOperation_Degree();

  /**
   * Returns the meta object for class '{@link org.xtext.example.iml.extendedIML.FilterOperation <em>Filter Operation</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Filter Operation</em>'.
   * @see org.xtext.example.iml.extendedIML.FilterOperation
   * @generated
   */
  EClass getFilterOperation();

  /**
   * Returns the meta object for class '{@link org.xtext.example.iml.extendedIML.BlurOperation <em>Blur Operation</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Blur Operation</em>'.
   * @see org.xtext.example.iml.extendedIML.BlurOperation
   * @generated
   */
  EClass getBlurOperation();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.iml.extendedIML.BlurOperation#getIntensity <em>Intensity</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Intensity</em>'.
   * @see org.xtext.example.iml.extendedIML.BlurOperation#getIntensity()
   * @see #getBlurOperation()
   * @generated
   */
  EAttribute getBlurOperation_Intensity();

  /**
   * Returns the meta object for class '{@link org.xtext.example.iml.extendedIML.EqualizeOperation <em>Equalize Operation</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Equalize Operation</em>'.
   * @see org.xtext.example.iml.extendedIML.EqualizeOperation
   * @generated
   */
  EClass getEqualizeOperation();

  /**
   * Returns the meta object for class '{@link org.xtext.example.iml.extendedIML.ShowOperation <em>Show Operation</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Show Operation</em>'.
   * @see org.xtext.example.iml.extendedIML.ShowOperation
   * @generated
   */
  EClass getShowOperation();

  /**
   * Returns the meta object for class '{@link org.xtext.example.iml.extendedIML.SaveOperation <em>Save Operation</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Save Operation</em>'.
   * @see org.xtext.example.iml.extendedIML.SaveOperation
   * @generated
   */
  EClass getSaveOperation();

  /**
   * Returns the factory that creates the instances of the model.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the factory that creates the instances of the model.
   * @generated
   */
  ExtendedIMLFactory getExtendedIMLFactory();

  /**
   * <!-- begin-user-doc -->
   * Defines literals for the meta objects that represent
   * <ul>
   *   <li>each class,</li>
   *   <li>each feature of each class,</li>
   *   <li>each enum,</li>
   *   <li>and each data type</li>
   * </ul>
   * <!-- end-user-doc -->
   * @generated
   */
  interface Literals
  {
    /**
     * The meta object literal for the '{@link org.xtext.example.iml.extendedIML.impl.ModelImpl <em>Model</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.iml.extendedIML.impl.ModelImpl
     * @see org.xtext.example.iml.extendedIML.impl.ExtendedIMLPackageImpl#getModel()
     * @generated
     */
    EClass MODEL = eINSTANCE.getModel();

    /**
     * The meta object literal for the '<em><b>Elements</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference MODEL__ELEMENTS = eINSTANCE.getModel_Elements();

    /**
     * The meta object literal for the '{@link org.xtext.example.iml.extendedIML.impl.AbstractElementImpl <em>Abstract Element</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.iml.extendedIML.impl.AbstractElementImpl
     * @see org.xtext.example.iml.extendedIML.impl.ExtendedIMLPackageImpl#getAbstractElement()
     * @generated
     */
    EClass ABSTRACT_ELEMENT = eINSTANCE.getAbstractElement();

    /**
     * The meta object literal for the '{@link org.xtext.example.iml.extendedIML.impl.ImporterImpl <em>Importer</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.iml.extendedIML.impl.ImporterImpl
     * @see org.xtext.example.iml.extendedIML.impl.ExtendedIMLPackageImpl#getImporter()
     * @generated
     */
    EClass IMPORTER = eINSTANCE.getImporter();

    /**
     * The meta object literal for the '{@link org.xtext.example.iml.extendedIML.impl.ImageImporterImpl <em>Image Importer</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.iml.extendedIML.impl.ImageImporterImpl
     * @see org.xtext.example.iml.extendedIML.impl.ExtendedIMLPackageImpl#getImageImporter()
     * @generated
     */
    EClass IMAGE_IMPORTER = eINSTANCE.getImageImporter();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute IMAGE_IMPORTER__NAME = eINSTANCE.getImageImporter_Name();

    /**
     * The meta object literal for the '<em><b>Imported Namespace</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute IMAGE_IMPORTER__IMPORTED_NAMESPACE = eINSTANCE.getImageImporter_ImportedNamespace();

    /**
     * The meta object literal for the '{@link org.xtext.example.iml.extendedIML.impl.DirImporterImpl <em>Dir Importer</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.iml.extendedIML.impl.DirImporterImpl
     * @see org.xtext.example.iml.extendedIML.impl.ExtendedIMLPackageImpl#getDirImporter()
     * @generated
     */
    EClass DIR_IMPORTER = eINSTANCE.getDirImporter();

    /**
     * The meta object literal for the '<em><b>Path Dir</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute DIR_IMPORTER__PATH_DIR = eINSTANCE.getDirImporter_PathDir();

    /**
     * The meta object literal for the '{@link org.xtext.example.iml.extendedIML.impl.OperatorImpl <em>Operator</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.iml.extendedIML.impl.OperatorImpl
     * @see org.xtext.example.iml.extendedIML.impl.ExtendedIMLPackageImpl#getOperator()
     * @generated
     */
    EClass OPERATOR = eINSTANCE.getOperator();

    /**
     * The meta object literal for the '<em><b>Var</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute OPERATOR__VAR = eINSTANCE.getOperator_Var();

    /**
     * The meta object literal for the '{@link org.xtext.example.iml.extendedIML.impl.RotateOperationImpl <em>Rotate Operation</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.iml.extendedIML.impl.RotateOperationImpl
     * @see org.xtext.example.iml.extendedIML.impl.ExtendedIMLPackageImpl#getRotateOperation()
     * @generated
     */
    EClass ROTATE_OPERATION = eINSTANCE.getRotateOperation();

    /**
     * The meta object literal for the '<em><b>Degree</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute ROTATE_OPERATION__DEGREE = eINSTANCE.getRotateOperation_Degree();

    /**
     * The meta object literal for the '{@link org.xtext.example.iml.extendedIML.impl.FilterOperationImpl <em>Filter Operation</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.iml.extendedIML.impl.FilterOperationImpl
     * @see org.xtext.example.iml.extendedIML.impl.ExtendedIMLPackageImpl#getFilterOperation()
     * @generated
     */
    EClass FILTER_OPERATION = eINSTANCE.getFilterOperation();

    /**
     * The meta object literal for the '{@link org.xtext.example.iml.extendedIML.impl.BlurOperationImpl <em>Blur Operation</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.iml.extendedIML.impl.BlurOperationImpl
     * @see org.xtext.example.iml.extendedIML.impl.ExtendedIMLPackageImpl#getBlurOperation()
     * @generated
     */
    EClass BLUR_OPERATION = eINSTANCE.getBlurOperation();

    /**
     * The meta object literal for the '<em><b>Intensity</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute BLUR_OPERATION__INTENSITY = eINSTANCE.getBlurOperation_Intensity();

    /**
     * The meta object literal for the '{@link org.xtext.example.iml.extendedIML.impl.EqualizeOperationImpl <em>Equalize Operation</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.iml.extendedIML.impl.EqualizeOperationImpl
     * @see org.xtext.example.iml.extendedIML.impl.ExtendedIMLPackageImpl#getEqualizeOperation()
     * @generated
     */
    EClass EQUALIZE_OPERATION = eINSTANCE.getEqualizeOperation();

    /**
     * The meta object literal for the '{@link org.xtext.example.iml.extendedIML.impl.ShowOperationImpl <em>Show Operation</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.iml.extendedIML.impl.ShowOperationImpl
     * @see org.xtext.example.iml.extendedIML.impl.ExtendedIMLPackageImpl#getShowOperation()
     * @generated
     */
    EClass SHOW_OPERATION = eINSTANCE.getShowOperation();

    /**
     * The meta object literal for the '{@link org.xtext.example.iml.extendedIML.impl.SaveOperationImpl <em>Save Operation</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.iml.extendedIML.impl.SaveOperationImpl
     * @see org.xtext.example.iml.extendedIML.impl.ExtendedIMLPackageImpl#getSaveOperation()
     * @generated
     */
    EClass SAVE_OPERATION = eINSTANCE.getSaveOperation();

  }

} //ExtendedIMLPackage
