/**
 * generated by Xtext 2.25.0
 */
package org.xtext.example.iml.extendedIML;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Fill Operation</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.iml.extendedIML.FillOperation#getTam <em>Tam</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.iml.extendedIML.ExtendedIMLPackage#getFillOperation()
 * @model
 * @generated
 */
public interface FillOperation extends Operator
{
  /**
   * Returns the value of the '<em><b>Tam</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Tam</em>' attribute.
   * @see #setTam(int)
   * @see org.xtext.example.iml.extendedIML.ExtendedIMLPackage#getFillOperation_Tam()
   * @model
   * @generated
   */
  int getTam();

  /**
   * Sets the value of the '{@link org.xtext.example.iml.extendedIML.FillOperation#getTam <em>Tam</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Tam</em>' attribute.
   * @see #getTam()
   * @generated
   */
  void setTam(int value);

} // FillOperation
