/**
 * generated by Xtext 2.25.0
 */
package org.xtext.example.iml.extendedIML;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Filter Operation</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see org.xtext.example.iml.extendedIML.ExtendedIMLPackage#getFilterOperation()
 * @model
 * @generated
 */
public interface FilterOperation extends Operator
{
} // FilterOperation
