/**
 * generated by Xtext 2.25.0
 */
package org.xtext.example.iml.extendedIML;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Importer</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see org.xtext.example.iml.extendedIML.ExtendedIMLPackage#getImporter()
 * @model
 * @generated
 */
public interface Importer extends AbstractElement
{
} // Importer
