/**
 * generated by Xtext 2.25.0
 */
package org.xtext.example.iml.extendedIML;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Operator</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see org.xtext.example.iml.extendedIML.ExtendedIMLPackage#getOperator()
 * @model
 * @generated
 */
public interface Operator extends AbstractElement
{
} // Operator
