/**
 * generated by Xtext 2.25.0
 */
package org.xtext.example.iml.extendedIML;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Rotate Operation</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.iml.extendedIML.RotateOperation#getDegree <em>Degree</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.iml.extendedIML.ExtendedIMLPackage#getRotateOperation()
 * @model
 * @generated
 */
public interface RotateOperation extends Operator
{
  /**
   * Returns the value of the '<em><b>Degree</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Degree</em>' attribute.
   * @see #setDegree(int)
   * @see org.xtext.example.iml.extendedIML.ExtendedIMLPackage#getRotateOperation_Degree()
   * @model
   * @generated
   */
  int getDegree();

  /**
   * Sets the value of the '{@link org.xtext.example.iml.extendedIML.RotateOperation#getDegree <em>Degree</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Degree</em>' attribute.
   * @see #getDegree()
   * @generated
   */
  void setDegree(int value);

} // RotateOperation
