/*
 * generated by Xtext 2.25.0
 */
package org.xtext.example.iml.ide;


/**
 * Use this class to register ide components.
 */
public class ExtendedIMLIdeModule extends AbstractExtendedIMLIdeModule {
}
