/*
 * generated by Xtext 2.25.0
 */
package org.xtext.example.iml.ide;

import com.google.inject.Guice;
import com.google.inject.Injector;
import org.eclipse.xtext.util.Modules2;
import org.xtext.example.iml.ExtendedIMLRuntimeModule;
import org.xtext.example.iml.ExtendedIMLStandaloneSetup;

/**
 * Initialization support for running Xtext languages as language servers.
 */
public class ExtendedIMLIdeSetup extends ExtendedIMLStandaloneSetup {

	@Override
	public Injector createInjector() {
		return Guice.createInjector(Modules2.mixin(new ExtendedIMLRuntimeModule(), new ExtendedIMLIdeModule()));
	}
	
}
